name: Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t actividad-docker .

      - name: Ejecutar contenedor
        run: docker run -d -p 3000:3000 --name actividad-docker actividad-docker

      - name: Esperar al servidor
        run: sleep 3

      - name: Mostrar salida de Docker
        run: |
          echo "## 🐳 Salida de Docker" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          docker logs actividad-docker 2>&1 >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Probar aplicación
        run: |
          respuesta=$(curl -s http://localhost:3000)

          echo "## 🌐 Respuesta de la aplicación" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          echo "$respuesta" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Ver contenedor
        run: |
          echo "## 📦 Contenedor" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          docker ps -a >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY